spring.application.name=VKApiBot

server.confirmation.token=37c82bcf
server.access.token=vk1.a.GGErJluOWuTGDtYCp4swpctlCKLIJnrkDtXIfrHvTXCejwSt80rjTveSnX2ee0F0tCWAfOfylwe7iV1xafu91LaDazRcWT9QYsF3f8br6LBBPvU-eRrmrobWt8BEATbpZQkpupp5doWCqX8gFkswe0naBYEHm8nLjui1vck589cX2jackrWnqT-ZocuyRSbh1OQf6MiC_asrQft3pSM1bQ

vk.api.version=5.236
vk.api.method.url=https://api.vk.com/method/
vk.api.send.message.method=messages.send
vk.api.get.user.method=users.get