spring.application.name=VKApiBot

server.confirmation.token=85c2f76d
server.access.token=vk1.a.EmYq7dbO5Rw_qJeqv91Cu3rHbczXdJbbrOr-XnHfvuOiGT9sQEyyx3j3RlR3B4AhIHHCoxWg-qyTEW14wh-Csht019FGzrVcLjX8dld4Uo-RkZo3UKakZhkXLP14sczbxFD_3m8zGZyTKexXtSNGJBiLDCr3dfXj6bbLTWQjQSdZ2qSOQZBz93mcQfEoImC_0QdbqF1xCrpQAUYa0rUMew

vk.api.version=5.236
vk.api.method.url=https://api.vk.com/method/
vk.api.send.message.method=messages.send
vk.api.get.user.method=users.get